//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewDocumento
    {
        public string secuencia { get; set; }
        public string nombre { get; set; }
        public string nombreUsuario { get; set; }
        public string Departamento_Origen { get; set; }
        public string Departamento_Destino { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
    }
}
